version: '3.9'
services:
  # backend:
  #   build: .
  #   ports:
  #     - 8000:3000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7.22
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: admin
  #     MYSQL_USER: suman
  #     MYSQL_PASSWORD: suman
  #     MYSQL_ROOT_PASSWORD: suman
  #   volumes:
  #     - .dbdata:/var/lib/mysql
  #   ports:
  #     - 33066:3306

  db:
    image: postgres
    restart: always
    hostname: suman
    environment:
      POSTGRES_USER: suman
      POSTGRES_PASSWORD: suman
      POSTGRES_DB: admin
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  .dbdata:
